# MDSC-302(P) Deep Learning Practicals

# Assignment-1
# Name    : Guru Prasanth R S
# Regd No : 240402008003

#  Chapter - 3 Tensors: Multidimensional arrays

## From Python Lists to PyTorch Tensors

In [1]:
# Creating a Python list with three float values
a = [1.0, 2.0, 1.0]

In [2]:
# Access the first element (remember: Python uses 0-based indexing)
a[0]

1.0

In [3]:
# Change the third element (index 2) to 3.0
a[2] = 3.0

# Display the updated list
a

[1.0, 2.0, 3.0]

## Constructing Our First Tensors

In [4]:
# Import the torch module
import torch

This creates a 1D tensor with 3 elements, each initialized to 1.0.


In [5]:
# Create a 1D tensor of size 3 filled with ones
a = torch.ones(3)

# Display the tensor
a

tensor([1., 1., 1.])

Accessing Elements

In [6]:
# Access the second element (index 1)
a[1]

tensor(1.)

Note: PyTorch returns a 0-dimensional tensor (also called a scalar tensor) when you index a single element.

In [7]:
# Convert a single tensor element to a Python float
print(float(a[1]))
a[1].item()  # Also returns 1.0

1.0


1.0

Modify an Element

In [8]:
# Change the third element (index 2) to 2.0
a[2] = 2.0

# Display the updated tensor
a

tensor([1., 1., 2.])

**NOTE : Python Lists vs PyTorch Tensors**

Python lists are collections of Python objects, which means:

- Each number is a separate object in memory.

- Less efficient for large-scale data or numerical computations.

PyTorch tensors (and NumPy arrays):

- Store unboxed C numeric types.

- Data is stored in contiguous memory (much more efficient).

- Ideal for working with large datasets or using the GPU.

**Example: Storing Coordinates in a Tensor**

Imagine we want to store the coordinates of a triangle with vertices at:

(4, 1)

(5, 3)

(2, 1)

We can do this using a 1D tensor, alternating X and Y coordinates.

**Method 1**: Initialize with torch.zeros() and manually assign

In [9]:
import torch

# Create a 1D tensor of size 6, filled with zeros
points = torch.zeros(6)

# Assign x and y values for 3 points
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

points

tensor([4., 1., 5., 3., 2., 1.])

**Method 2**: Use a list directly

In [10]:
# Initialize the same tensor more concisely using a list
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

Access individual coordinates

In [11]:
# Get the x and y coordinates of the first point
float(points[0]), float(points[1])

(4.0, 1.0)

Making It More Practical: Use a 2D Tensor

Rather than storing (x, y) pairs in a flat list, we can use a 2D tensor where each row is a point.


In [12]:
# Each sublist represents a 2D point (x, y)
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

Check the shape of the tensor

In [13]:
# Shape = (3 rows, 2 columns)
points.shape

torch.Size([3, 2])

Create a blank 2D tensor using torch.zeros()

In [14]:
# Create a 3x2 tensor filled with zeros
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Accessing Elements in a 2D Tensor

In [15]:
# Reset tensor to actual values
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])

# Access the Y-coordinate (1st column) of the 0th point (first row)
points[0, 1]

tensor(1.)

Get the full coordinates of a point

In [16]:
# Get all coordinates of the 0th point
points[0]

tensor([4., 1.])

## Indexing tensors

Indexing in Python

In [17]:
# Standard Python list
some_list = list(range(6))  # [0, 1, 2, 3, 4, 5]

# All elements
print("All elements : ",some_list[:])         # → [0, 1, 2, 3, 4, 5]

# From index 1 to 3 (exclusive of 4)
print("From index 1 to 3 : ",some_list[1:4] )      # → [1, 2, 3]

# From index 1 to end
print("From index 1 to end : ",some_list[1:])        # → [1, 2, 3, 4, 5]

# From start to index 4 (exclusive)
print("From start to index 4 : ",some_list[:4])        # → [0, 1, 2, 3]

# All except last
print("All except last : ",some_list[:-1] )      # → [0, 1, 2, 3, 4]

# From index 1 to 3, step size 2
print("From index 1 to 3, step size 2 : ",some_list[1:4:2] )    # → [1, 3]

All elements :  [0, 1, 2, 3, 4, 5]
From index 1 to 3 :  [1, 2, 3]
From index 1 to end :  [1, 2, 3, 4, 5]
From start to index 4 :  [0, 1, 2, 3]
All except last :  [0, 1, 2, 3, 4]
From index 1 to 3, step size 2 :  [1, 3]


Indexing in PyTorch Tensors

In [18]:
import torch

# Define a 2D tensor of 3 points (each with x and y coordinates)
points = torch.tensor([
    [4.0, 1.0],
    [5.0, 3.0],
    [2.0, 1.0]
])

In [19]:
# All rows except the first
print("All rows except the first : \n",points[1:])

# All rows after the first, all columns
print("All rows after the first, all columns : \n",points[1:, :])

# All rows after the first, only the first column (x values)
print("All rows after the first, only the first column (x values) : \n",points[1:, 0])

# Adds a new dimension at the front (acts like unsqueeze)
print("Adds a new dimension at the front : \n",points[None])

# The above is same as the below
points.unsqueeze(0)

All rows except the first : 
 tensor([[5., 3.],
        [2., 1.]])
All rows after the first, all columns : 
 tensor([[5., 3.],
        [2., 1.]])
All rows after the first, only the first column (x values) : 
 tensor([5., 2.])
Adds a new dimension at the front : 
 tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])


tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## Named Tensors in PyTorch

Why Named Tensors?

When working with high-dimensional tensors (e.g., images, batches, channels), it becomes difficult to remember what each axis represents.

Named tensors:

- Help you avoid bugs by giving names to dimensions (e.g., 'channels', 'rows', 'columns')

- Make operations more readable and safer



simulate RGB image data using torch.randn.

In [20]:
import torch

# Simulate a single image: [channels=3, height=5, width=5]
img_t = torch.randn(3, 5, 5)

# Grayscale conversion weights (typical luma values)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

Simulate a Batch of 2 Images

In [21]:
# Simulate a batch of 2 images: [batch=2, channels=3, height=5, width=5]
batch_t = torch.randn(2, 3, 5, 5)

Basic Grayscale Conversion (Unweighted)

In [22]:
# Compute mean across channel dimension (third from the end = -3)
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)

img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

Apply Grayscale Weights Using Broadcasting

In [23]:
# Adjust shape to [3, 1, 1] to match the image format [3, H, W]
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

# Apply weighted grayscale conversion
img_weights = img_t * unsqueezed_weights
batch_weights = batch_t * unsqueezed_weights

img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)

batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

Einsum

In [24]:
# Fancy shorthand using einsum for same result
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw', batch_t, weights)

batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

Named Tensors in Action

Add Names to Dimensions

In [25]:
# Create a named tensor directly
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/tmp/ipython-input-25-2302798016.py:2: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /pytorch/c10/core/TensorImpl.h:1935.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

Refine Names for Existing Tensors

In [26]:
# Add names to existing tensors
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')

print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


Align Weights to Match Dimensions

In [27]:
# Align weights_named with img_named (adds singleton dims and reorders)
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

Use Named Dimension in Operations

In [28]:
# Multiply and sum over the 'channels' dimension
gray_named = (img_named * weights_aligned).sum('channels')
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

Broadcast Name Mismatch Error

In [29]:
# This will raise an error due to name misalignment
gray_named = (img_named[..., :3] * weights_named).sum('channels')

RuntimeError: Error when attempting to broadcast dims ['channels', 'rows', 'columns'] and dims ['channels']: dim 'columns' and dim 'channels' are at the same position from the right but do not match.

Drop Names to Return to Unnamed Tensors

In [30]:
# Remove names to use tensor in code expecting unnamed tensors
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

# Tensor Element Types

Why care about data types?

While Python allows flexibility with number types, PyTorch requires all elements of a tensor to have the same numeric type, for performance and memory efficiency.



Creating Tensors with Different dtypes

In [31]:
# Create a 10x2 tensor of 1.0s with double precision
double_points = torch.ones(10, 2, dtype=torch.double)

# Create a 2x2 tensor of 16-bit integers (short)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

# Check dtype
print("Double tensor dtype:", double_points.dtype)
print("Short tensor dtype:", short_points.dtype)

Double tensor dtype: torch.float64
Short tensor dtype: torch.int16


Managing a Tensor's dtype Attribute

Method 1: Use casting methods

In [32]:
# Use casting methods directly
double_points = torch.zeros(10, 2).double()  # to double
short_points = torch.ones(10, 2).short()     # to short

Method 2:Use .to() for conversion

In [33]:
# More flexible and general
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

Inspect dtype of any tensor

In [34]:
print("dtype of short_points:", short_points.dtype)

dtype of short_points: torch.int16


Mixing Types — Auto Promotion

If you multiply float64 and int16, PyTorch will promote to the higher precision type.

In [35]:
# 64-bit float tensor
points_64 = torch.rand(5, dtype=torch.double)

# Convert to int16
points_short = points_64.to(torch.short)

# Multiply — result is float64 with values zeroed (int * float = float)
result = points_64 * points_short
print("Result:", result)
print("dtype:", result.dtype)

Result: tensor([0., 0., 0., 0., 0.], dtype=torch.float64)
dtype: torch.float64


## The Tensor API

Example: Transposing a Tensor

In [36]:
import torch

a = torch.ones(3, 2)

# Method 1: Using torch module
a_torch = torch.transpose(a, 0, 1)

# Method 2: Using tensor method
a_method = a.transpose(0, 1)

print("Original shape:", a.shape)
print("Transposed shape (torch):", a_torch.shape)
print("Transposed shape (method):", a_method.shape)

Original shape: torch.Size([3, 2])
Transposed shape (torch): torch.Size([2, 3])
Transposed shape (method): torch.Size([2, 3])


## Tensors: Scenic Views of Storage

What's under the hood?

Every torch.Tensor doesn't directly "own" memory. Instead, it references a Storage, which is a contiguous block of memory (1D array) storing the actual numerical data.

This design enables multiple tensors to share the same memory, accessing it differently using shape, offset, and stride.

Indexing into Storage

In [37]:
import torch

# Create a 2D tensor of shape (3, 2)
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])

# View the underlying storage (a flat 1D array)
points.storage()

/tmp/ipython-input-37-479134480.py:9: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

Indexing into storage directly

In [38]:
points_storage = points.storage()

# Get the first element in raw storage
print(points_storage[0])  # 4.0

# Get the second element
print(points_storage[1])  # 1.0

4.0
1.0


Mutating Storage Affects Tensor!

In [39]:
# Changing the storage will change the tensor values too
points_storage[0] = 2.0

# Now points tensor is changed!
print(points)

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])


Modifying Stored Values: In-place Operations

In-place zeroing of a tensor

In [40]:
a = torch.ones(3, 2)   # Create tensor of all ones
a.zero_()              # In-place operation (with "_")
print(a)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


## Tensor Metadata: Size, Offset, and Stride

Tensors are just views into a block of memory, and how we interpret that memory is governed by:

size → Shape (rows, columns)

offset → Where to start reading

stride → How to jump between elements along each axis

Views of Another Tensor’s Storage

In [41]:
import torch

# Define a 2D tensor with 3 rows and 2 columns
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])

# Extract the second row (index 1)
second_point = points[1]

In [42]:
# Where in the storage this tensor starts (index 1 * 2 cols = 2)
second_point.storage_offset()

2

In [43]:
# Its size (it's a 1D tensor of 2 elements)
second_point.size()

torch.Size([2])

In [44]:
# Shape is same as size for tensors
second_point.shape

torch.Size([2])

In [45]:
# Stride tells how many elements to skip to move along each dimension
points.stride()  # Original 2D tensor


(2, 1)

Understanding View Behavior

In [46]:
second_point = points[1]
print(second_point.size())            # torch.Size([2])
print(second_point.storage_offset())  # 2
print(second_point.stride())         # (1,)

torch.Size([2])
2
(1,)


Changing a view affects the original

In [47]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])

second_point = points[1]
second_point[0] = 10.0
print(points)

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])


To avoid this, use .clone():

In [48]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])

second_point = points[1].clone()
second_point[0] = 10.0

print(points)  # original is unchanged

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


Transposing Without Copying

In [49]:
points = torch.tensor([[4.0, 1.0],
                       [5.0, 3.0],
                       [2.0, 1.0]])

points_t = points.t()  # transpose for 2D tensors

In [50]:
print(points_t)  # Shape becomes (2, 3)

tensor([[4., 5., 2.],
        [1., 3., 1.]])


Do both share the same memory?

In [51]:
id(points.storage()) == id(points_t.storage())  # True

True

In [52]:
# Check stride of both
print("points.stride():", points.stride())     # (2, 1)
print("points_t.stride():", points_t.stride()) # (1, 2)

points.stride(): (2, 1)
points_t.stride(): (1, 2)


Transposing in Higher Dimensions

In [53]:
some_t = torch.ones(3, 4, 5)  # Shape: (3, 4, 5)

# Transpose dimension 0 and 2
transpose_t = some_t.transpose(0, 2)

print("Original shape:", some_t.shape)       # torch.Size([3, 4, 5])
print("Transposed shape:", transpose_t.shape) # torch.Size([5, 4, 3])

Original shape: torch.Size([3, 4, 5])
Transposed shape: torch.Size([5, 4, 3])


In [54]:
print("Original stride:", some_t.stride())       # (20, 5, 1)
print("Transposed stride:", transpose_t.stride()) # (1, 5, 20)

Original stride: (20, 5, 1)
Transposed stride: (1, 5, 20)


Contiguous Tensors

In [55]:
print(points.is_contiguous())       # True
print(points_t.is_contiguous())     # False

True
False


Making a tensor contiguous

In [56]:
points_t_cont = points_t.contiguous()

In [57]:
print("Old stride:", points_t.stride())          # (1, 2)
print("New stride:", points_t_cont.stride())     # (3, 1)

Old stride: (1, 2)
New stride: (3, 1)


In [58]:
# Check storage: values are reshuffled for row-wise layout
print("Old storage:", points_t.storage())
print("New storage:", points_t_cont.storage())

Old storage:  4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
New storage:  4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]
