# The following are to be implemented using numpy
## - Eigenvalues, Eigenvectors


In [1]:
import numpy as np

# Input the matrix from the user
def input_matrix():
    n = int(input("Enter the size of the square matrix (n x n): "))
    print("Enter the matrix row by row, values space-separated:")
    A = []
    for i in range(n):
        row = list(map(float, input(f"Enter row {i+1}: ").split()))
        if len(row) != n:
            raise ValueError("Each row must contain exactly {} elements.".format(n))
        A.append(row)
    return np.array(A)

# Compute eigenvalues and eigenvectors
matrix = input_matrix()
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Enter the size of the square matrix (n x n): 3
Enter the matrix row by row, values space-separated:
Enter row 1: 4 5 6
Enter row 2: 7 8 9
Enter row 3: 1 2 3
Eigenvalues: [ 1.43738635e+01 -3.43259130e-15  6.26136458e-01]
Eigenvectors:
 [[-0.51406621 -0.40824829 -0.04901632]
 [-0.8359418   0.81649658 -0.75357015]
 [-0.19219061 -0.40824829  0.65553752]]


## - SVD

In [2]:
import numpy as np

def input_matrix():
    n = int(input("Enter the size of the square matrix (n x n): "))
    print("Enter the matrix row by row, values space-separated:")
    A = []
    for i in range(n):
        row = list(map(float, input(f"Enter row {i+1}: ").split()))
        if len(row) != n:
            raise ValueError("Each row must contain exactly {} elements.".format(n))
        A.append(row)
    return np.array(A)

# Input the matrix from the user
matrix = input_matrix()

# Perform SVD
U, S, Vt = np.linalg.svd(matrix)

print("U matrix:\n", U)
print("Singular values:", S)
print("V^T matrix:\n", Vt)


Enter the size of the square matrix (n x n): 3
Enter the matrix row by row, values space-separated:
Enter row 1: 1 2 3
Enter row 2: 4 5 6
Enter row 3: 7 8 9
U matrix:
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values: [1.68481034e+01 1.06836951e+00 4.41842475e-16]
V^T matrix:
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


## - Eigenfaces

In [5]:
import numpy as np

# Function to input a data matrix (flattened images)
def input_matrix():
    n = int(input("Enter the number of images (rows in the matrix): "))  # Number of images
    m = int(input("Enter the number of pixels per image (columns in the matrix): "))  # Number of pixels

    print("Enter the image data row by row (flattened), values space-separated:")
    data_matrix = []
    for i in range(n):
        row = list(map(float, input(f"Enter image {i + 1}: ").split()))
        if len(row) != m:
            raise ValueError(f"Each row must contain exactly {m} pixels.")
        data_matrix.append(row)

    return np.array(data_matrix)

# Main program to compute eigenfaces
try:
    # Step 1: Input the data matrix
    data_matrix = input_matrix()

    # Step 2: Subtract the mean
    mean_face = np.mean(data_matrix, axis=0)
    centered_data = data_matrix - mean_face

    # Step 3: Perform SVD
    U, S, Vt = np.linalg.svd(centered_data, full_matrices=False)

    # Step 4: Extract the eigenfaces (first 10 eigenfaces)
    eigenfaces = Vt[:10]

    # Print the results
    print("Eigenfaces (first 10 principal components):")
    print(eigenfaces)

except ValueError as e:
    print("Error:", e)


Enter the number of images (rows in the matrix): 3
Enter the number of pixels per image (columns in the matrix): 4
Enter the image data row by row (flattened), values space-separated:
Enter image 1: 1 2 3 4
Enter image 2: 5 6 7 8
Enter image 3: 9 10 11 12
Eigenfaces (first 10 principal components):
[[-5.00000000e-01 -5.00000000e-01 -5.00000000e-01 -5.00000000e-01]
 [-8.66025404e-01  2.88675135e-01  2.88675135e-01  2.88675135e-01]
 [-4.16333634e-17 -5.77350269e-01  7.88675135e-01 -2.11324865e-01]]


## - Linear Regression


In [4]:
import numpy as np

def input_matrix_and_vector():
    n = int(input("Enter the number of samples (rows in the matrix): "))
    m = int(input("Enter the number of features (columns in the matrix): "))

    # Input the feature matrix X
    print("Enter the feature matrix row by row, values space-separated:")
    X = []
    for i in range(n):
        row = list(map(float, input(f"Enter row {i+1}: ").split()))
        if len(row) != m:
            raise ValueError("Each row must contain exactly {} elements.".format(m))
        X.append(row)

    # Input the output vector y
    print("Enter the output vector (space-separated):")
    y = list(map(float, input().split()))
    if len(y) != n:
        raise ValueError("The output vector must contain exactly {} elements.".format(n))

    return np.array(X), np.array(y)

# Input the data
X, y = input_matrix_and_vector()

# Compute theta (coefficients) using the normal equation
theta = np.linalg.inv(X.T @ X) @ X.T @ y

print("Linear regression coefficients (theta):", theta)


Enter the number of samples (rows in the matrix): 3
Enter the number of features (columns in the matrix): 2
Enter the feature matrix row by row, values space-separated:
Enter row 1: 1 2
Enter row 2: 2 3
Enter row 3: 3 5
Enter the output vector (space-separated):
3 5 8
Linear regression coefficients (theta): [1. 1.]


## - Matrix Exponential

In [3]:
import numpy as np
from scipy.linalg import expm

# Input the matrix from the user
matrix = input_matrix()

# Compute the matrix exponential
matrix_exponential = expm(matrix)

print("Matrix exponential:\n", matrix_exponential)


Enter the size of the square matrix (n x n): 3
Enter the matrix row by row, values space-separated:
Enter row 1: 1 2 3
Enter row 2: 4 5 6
Enter row 3: 7 8 9
Matrix exponential:
 [[1118906.69941319 1374815.06293581 1630724.42645843]
 [2533881.04189897 3113415.03138055 3692947.02086214]
 [3948856.38438476 4852012.9998253  5755170.61526585]]
